### ISSUE TITLE
Мастер-класс по Go и Kubernetes (РИТ++ 2017)

### ISSUE THREAD

**Issue by rumyantseva** [hH39797J/golang-videos-ru#10]
Тезисы здесь: http://ritfest.ru/2017/abstracts/2564
Видео здесь: https://youtu.be/0ndWw1udpsA?t=7m16s
Слайды здесь: https://github.com/k8s-community/rit-2017-slides

**Comment by hH39797J** [comment]
6 июня, 13:00

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#%D0%A0%D0%98%D0%A2-2017

**Comment by rumyantseva** [comment]
Спасибо!
