### ISSUE TITLE
Go 1.8 release party (16.02.2017)

### ISSUE THREAD

**Issue by AterCattus** [hH39797J/golang-videos-ru#13]
https://www.youtube.com/playlist?list=PLknJ4Vr6efQEC9g8MIJopLmTZ0b_MXlYh

**Comment by hH39797J** [comment]
https://habrahabr.ru/company/avito/blog/322384/

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#go-18-release-party-moscow
