### ISSUE TITLE
Go 1.10 Release Party @ Badoo 24.02.2018

### ISSUE THREAD

**Issue by Nklya** [hH39797J/golang-videos-ru#18]
Вышло видео с недавнего Go 1.10 Release Party @ Badoo 24.02.2018

Плейлист https://www.youtube.com/watch?v=RLR1C8xXiiA&list=PL3xVZC4USRNQbOtJ9OMyvTARfXOv3vwD8

**Comment by hH39797J** [comment]
Добрый вечер.

Спасибо, уже добавлено - https://github.com/hH39797J/golang-videos-ru#go-110-release-party--badoo

**Comment by Nklya** [comment]
Спасибо, не заметил.
