### ISSUE TITLE
GDG DevFest 2017

### ISSUE THREAD

**Issue by Ragnar-BY** [hH39797J/golang-videos-ru#23]
GDG DevFest 2017 Minsk
https://devfest.by/
Проводился 25 ноября 2017 года
Доклады по Golang:
https://www.youtube.com/watch?v=IJyBkIwPPps
https://www.youtube.com/watch?v=gohIdIKBmzg
https://www.youtube.com/watch?v=PYD6zPD2Sv0

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#gdg-devfest-minsk-2017
