### ISSUE TITLE
Оптимизация размера бинарников в Go

### ISSUE THREAD

**Issue by KosToZyB** [hH39797J/golang-videos-ru#26]
Открытая лекция: https://www.youtube.com/watch?v=HpriPuIfrGE

**Comment by Quasilyte** [comment]
Качество звука там конечно своеобразное.

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D1%8B%D0%B5-%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B
