### ISSUE TITLE
Go 1.9 Release Party

### ISSUE THREAD

**Issue by AlekSi** [hH39797J/golang-videos-ru#4]
https://www.meetup.com/Golang-Moscow/events/243355045/
https://www.youtube.com/watch?v=vV5Lqq2RBy8
https://www.youtube.com/watch?v=eCMkwFHCQqI

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#go-19-release-party-%D0%BB%D1%83%D1%87%D1%88%D0%B5-%D0%BF%D0%BE%D0%B7%D0%B4%D0%BD%D0%BE-%D1%87%D0%B5%D0%BC-%D0%BD%D0%B8%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0
