### ISSUE TITLE
Лекции Техносферы: Программирование на Go

### ISSUE THREAD

**Issue by Nklya** [hH39797J/golang-videos-ru#5]
Возможно есть смысл добавить мейлрушные лекции
https://habrahabr.ru/company/mailru/blog/327966/

**Comment by hH39797J** [comment]
Добрый день.

Лично я не стал смотреть эти лекции после прочтения [комментария](https://habrahabr.ru/company/mailru/blog/327966/#comment_10210598) со следующим содержанием:

> Простите, но уровень лекций — «ниже плинтуса». Может, это слишком субъективно, но я не смог досмотреть ни одной лекции. Хватило терпения только на 3. Я понимаю — парни волнуются, они разработчики, а не преподаватели. Но тем более тогда лучше сделать публичную версию специально отснятой — с монтажем, дублями и т.п. Видео и так очень отстает от книг в плане скорости подачи информации, а в этих лекциях скорость становится просто черепашьей, к сожалению. ИМХО, книга Кернигана и Донована за аналогичное время даст больше информации и основы go будут понятнее.

Причём этот комментарий собрал больше всего "+".

Оставляю эти лекции с низким приоритетом.

И спрошу совета в [golang-ru.slack.com](golang-ru.slack.com).

**Comment by Nklya** [comment]
Добрый день.
Я их тоже не смотрел))
Просто вспомнил, что видел где-то в ленте.

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D1%8B%D0%B5-%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B
