### ISSUE TITLE
Стачка 2017

### ISSUE THREAD

**Issue by AlekSi** [hH39797J/golang-videos-ru#6]
https://nastachku.ru/archive/2017/index.php
https://www.youtube.com/watch?v=xRs1gN9BCVw (https://speakerdeck.com/aleksi/profilirovaniie-i-optimizatsiia-proghramm-na-go)
https://www.youtube.com/watch?v=MitOZ3Bx6QE

Возможно, там было что-то ещё про Go.

**Comment by hH39797J** [comment]
STACHKA 2017
April 14-15

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#%D0%A1%D1%82%D0%B0%D1%87%D0%BA%D0%B0-2017
