### ISSUE TITLE
Митап в Lazada

### ISSUE THREAD

**Issue by AlekSi** [hH39797J/golang-videos-ru#7]
https://www.youtube.com/playlist?list=PLsWUapro5DC3DPPqZNA8UQnpoNas2Khn6
https://speakerdeck.com/aleksi/what-the-fuzz

**Comment by hH39797J** [comment]
http://techblog.lazada.com/meetup/go/cockroachdb/profiling/2017/06/26/lazada-golang-meetup.html
25/05/2017

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#golang-meetup-at-lazada
