### ISSUE TITLE
Весенний Go

### ISSUE THREAD

**Issue by AlekSi** [hH39797J/golang-videos-ru#8]
https://www.youtube.com/playlist?list=PL3xVZC4USRNShnrPVbZAMJNTdA36TmNZv
https://speakerdeck.com/aleksi/reform-put-k-luchshiemu-orm

**Comment by hH39797J** [comment]
https://www.meetup.com/Golang-Moscow/events/230289501/
May 14, 2016

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/golang-videos-ru#%D0%92%D0%B5%D1%81%D0%B5%D0%BD%D0%BD%D0%B8%D0%B9-go
