### ISSUE TITLE
Ещё митап

### ISSUE THREAD

**Issue by AlekSi** [hH39797J/golang-videos-ru#9]
https://www.youtube.com/playlist?list=PL3xVZC4USRNRD2U7ZASvzaUQdngBanrW1

**Comment by hH39797J** [comment]
https://www.meetup.com/Golang-Moscow/events/221706352/
April 23, 2015

**Comment by hH39797J** [comment]
Добрый день.

Было принято решение ограничить период сбора ссылок на видео (https://github.com/hH39797J/golang-videos-ru/commit/88d5c49a7154dd2b9786c00576ca3bf2689fa27c).

Видео за 2015 год считается довольно старым и добавлено не будет.
Извините за сложившуюся ситуацию.

Спасибо за участие.

**Comment by fedir** [comment]
А по мне так, самое оно. Спасибо за ссылки !
